language: python
python: "3.6"
env:
  - TOX_ENV=py36
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py27
install:
  - pip install -e .
  - pip install tox
  - pip install Mako
  - pip install python-coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
sudo: false
